{{ $fullName :=  include "bitwarden.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitwarden.fullname" . }}-mssql
  labels:
    app.kubernetes.io/name: {{ include "bitwarden.name" . }}
    helm.sh/chart: {{ include "bitwarden.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: mssql
type: Opaque
data:
  sa-password: {{ .Values.mssql.saPassword | b64enc | quote }}
  connection-string: {{ (printf "Data Source=tcp:%s-mssql,1433;Initial Catalog=vault;Persist Security Info=False;User ID=sa;Password=%s;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True" $fullName .Values.mssql.saPassword) | b64enc | quote }}
