apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitwarden.fullname" . }}-nginx
  labels:
    app.kubernetes.io/name: {{ include "bitwarden.name" . }}
    helm.sh/chart: {{ include "bitwarden.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: nginx
data:
  default.conf: |
    server {
      listen 8080;
      server_name {{ .Values.global.host }};

      include /etc/nginx/security-headers-ssl.conf;
      include /etc/nginx/security-headers.conf;

      location / {
        proxy_pass http://{{ include "bitwarden.fullname" . }}-web:5000/;
        include /etc/nginx/security-headers-ssl.conf;
        include /etc/nginx/security-headers.conf;
        add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://haveibeenpwned.com https://www.gravatar.com; child-src 'self' https://*.duosecurity.com; frame-src 'self' https://*.duosecurity.com; connect-src 'self' wss://bitwarden.ekreative.com https://haveibeenpwned.com https://api.pwnedpasswords.com;";
        add_header X-Frame-Options SAMEORIGIN;
      }

      location = /app-id.json {
        proxy_pass http://{{ include "bitwarden.fullname" . }}-web:5000/app-id.json;
        include /etc/nginx/security-headers-ssl.conf;
        include /etc/nginx/security-headers.conf;
        proxy_hide_header Content-Type;
        add_header Content-Type $fido_content_type;
      }

      location = /duo-connector.html {
        proxy_pass http://{{ include "bitwarden.fullname" . }}-web:5000/duo-connector.html;
      }

      location = /u2f-connector.html {
        proxy_pass http://{{ include "bitwarden.fullname" . }}-web:5000/u2f-connector.html;
      }

      location /attachments/ {
        proxy_pass http://{{ include "bitwarden.fullname" . }}-attachments:5000/;
      }

      location /api/ {
        proxy_pass http://{{ include "bitwarden.fullname" . }}-api:5000/;
      }

      location /identity/ {
        proxy_pass http://{{ include "bitwarden.fullname" . }}-identity:5000/;
      }

      location /icons/ {
        proxy_pass http://{{ include "bitwarden.fullname" . }}-icons:5000/;
      }

      location /notifications/ {
        proxy_pass http://{{ include "bitwarden.fullname" . }}-notifications:5000/;
      }

      location /notifications/hub {
        proxy_pass http://{{ include "bitwarden.fullname" . }}-notifications:5000/hub;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
      }

      location /admin {
        proxy_pass http://{{ include "bitwarden.fullname" . }}-admin:5000;
        include /etc/nginx/security-headers-ssl.conf;
        include /etc/nginx/security-headers.conf;
        add_header X-Frame-Options SAMEORIGIN;
      }
    }
